import type { InfoItem } from "@/lib/domain/types";

// Seed 정보 아이템. Populated for now by hand to demonstrate the 6-facet
// browser; the real pipeline (kakao-daily 스크래퍼 포팅 → facet 태깅 →
// Firestore) replaces this later, same seed-fallback pattern as content/cards.
export const INFO_ITEMS: InfoItem[] = [
  {
    id: "serii-seonon-2025",
    type: "source",
    category: "record",
    level: "both",
    grade: "all",
    source: "서교연",
    timing: "recent",
    title: "[서교연] 중학교 서·논술형 평가 방안 연구",
    summary: "서울교육연구정보원이 낸 서·논술형 평가 설계 연구 책자(원문 PDF).",
    url: "https://drive.google.com/",
    publishedAt: "2026-02-19",
  },
  {
    id: "moe-teukseonggo-2026",
    type: "source",
    category: "admission",
    level: "high",
    grade: "h3",
    source: "교육부",
    timing: "recent",
    title: "협약형 특성화고 16개교 선정 (교육부 보도자료)",
    summary: "지역 맞춤형 기술인재 양성 협약형 특성화고 선정 결과 원문.",
    url: "https://drive.google.com/",
    publishedAt: "2026-06-08",
  },
  {
    id: "kice-june-mock-result",
    type: "briefing",
    category: "result",
    level: "high",
    grade: "h3",
    source: "평가원",
    timing: "recent",
    title: "6월 모의평가 성적 7월 1일 발표",
    summary: "2027학년도 수능 6월 모평 성적 통지 일정. 영역별 위치 점검 시점.",
    url: "https://www.suneung.re.kr/",
    publishedAt: "2026-06-13",
  },
  {
    id: "kcue-nonsul-plan-2027",
    type: "briefing",
    category: "admission",
    level: "high",
    grade: "h3",
    source: "대교협",
    timing: "recent",
    title: "대교협, 2027 대입 논술 전형 시행계획 안내",
    summary: "논술 실시 대학·일정 개괄. 지원 전략 수립 전 확인할 기준 자료.",
    url: "https://www.adiga.kr/",
    publishedAt: "2026-06-11",
  },
  {
    id: "explainer-yonsei-nonsul-2022",
    type: "explainer",
    category: "essay",
    level: "high",
    grade: "h3",
    source: "현장교사",
    timing: "evergreen",
    title: "연세대 2022 인문 논술 — 통계 자료 해석 문항 뜯어보기",
    summary: "제시된 통계로 주장을 비판·추론하는 문항. 요구 사고 과정 해설.",
    url: "/card/explainer-yonsei-nonsul-2022",
    publishedAt: "2026-05-30",
  },
  {
    id: "explainer-2028-suneung",
    type: "explainer",
    category: "admission",
    level: "high",
    grade: "h2",
    source: "현장교사",
    timing: "evergreen",
    title: "2028 대입 개편 — 통합형 수능, 무엇이 바뀌나",
    summary: "선택과목 폐지·통합형 출제의 방향과 현재 고2에게의 의미.",
    url: "/card/explainer-2028-suneung",
    publishedAt: "2026-05-24",
  },
  {
    id: "explainer-saeteuk",
    type: "explainer",
    category: "record",
    level: "high",
    grade: "all",
    source: "현장교사",
    timing: "evergreen",
    title: "학생부 세특, 평가자는 무엇을 보나",
    summary: "탐구의 자기주도성·연결성. 좋은 세특의 조건을 예시로 정리.",
    url: "/card/explainer-saeteuk",
    publishedAt: "2026-05-18",
  },
  {
    id: "explainer-middle-summer",
    type: "explainer",
    category: "career",
    level: "middle",
    grade: "middle",
    source: "현장교사",
    timing: "period",
    title: "중학생 진로탐색, 여름방학을 이렇게 쓰자",
    summary: "자유학기 연계 진로체험·기록 팁. 방학 중 실천 가능한 활동 중심.",
    url: "/card/explainer-middle-summer",
    publishedAt: "2026-06-25",
  },
  {
    id: "dataset-ipgyeol-2026",
    type: "data",
    category: "result",
    level: "high",
    grade: "h3",
    source: "대교협",
    timing: "evergreen",
    title: "주요대 수시 입결·경쟁률 정리표",
    summary: "여러 대학을 한 표로 정리한 데이터셋. 챗봇이 근거로 검색.",
    url: "/datasets/dataset-ipgyeol-2026",
    publishedAt: "2026-04-30",
  },
  {
    id: "gov-jinro-contest",
    type: "source",
    category: "contest",
    level: "both",
    grade: "all",
    source: "시도교육청",
    timing: "recent",
    title: "청소년 진로 탐구 공모전 안내 (교육청)",
    summary: "학생 대상 진로 탐구·발표 공모전 요강. 신청 기간·양식 포함.",
    url: "https://drive.google.com/",
    publishedAt: "2026-06-10",
  },
];
